export const cardData = [
	{
		type: 'Total Profit',
		percentage: '50.43%',
		arrow: '/assets/admin/dashboard/uparrow.svg',
		graph: '/assets/admin/dashboard/graph1.svg',
		price: '329.50',
	},
	{
		type: 'Total Revenue',
		percentage: '12.32%',
		arrow: '/assets/admin/dashboard/uparrow.svg',
		graph: '/assets/admin/dashboard/graph1.svg',
		price: '200.00',
	},
	{
		type: 'Total Visitors',
		percentage: '10.89%',
		arrow: '/assets/admin/dashboard/downarrow.svg',
		graph: '/assets/admin/dashboard/graph3.svg',
		price: '200.00',
	},
	{
		type: 'Product Sold',
		percentage: '20.92%',
		arrow: '/assets/admin/dashboard/uparrow.svg',
		graph: '/assets/admin/dashboard/graph4.svg',
		price: '200.00',
	},
];

export const orderCardData = [
	{
		type: 'Total Profit',
		percentage: '50.43%',
		arrow: '/assets/admin/dashboard/uparrow.svg',
		graph: '/assets/admin/dashboard/graph1.svg',
		price: '329.50',
	},
	{
		type: 'Total Revenue',
		percentage: '12.32%',
		arrow: '/assets/admin/dashboard/uparrow.svg',
		graph: '/assets/admin/dashboard/graph1.svg',
		price: '200.00',
	},
];
export const orderTableData = [
	{
		id: 12809,
		product: 'Apple Macbook Pro lorem20 dk...',
		order: '20/03/2023,01:10',
		status: 'Waiting Payment',
		Qty: 'x1',
		price: '40000000012.99',
		color: '#DD6107',
		image: '/assets/admin/dashboard/user2.png',
		customer: 'Omar Griffith',
	},
	{
		id: 12808,
		product: 'iBox iPhone 14Pro...',
		order: '20/03/2023,01:10',
		status: 'Transition Done',
		Qty: 'x1',
		price: '2.092',
		customer: 'Omar Griffith',
		image: '/assets/admin/dashboard/user3.png',
		color: '#10B860',
	},
	{
		id: 12807,
		product: 'Apple Macbook Pro...',
		order: '20/03/2023,01:10',
		status: 'Transition Done',
		Qty: 'x1',
		price: '1.089',
		customer: 'Omar Griffith',
		image: '/assets/admin/dashboard/user4.png',
		color: '#10B860',
	},
	{
		id: 12806,
		product: 'Apple Macbook Pro...',
		order: '20/03/2023,01:10',
		status: 'Delivery to Cust',
		Qty: 'x3',
		price: '833',
		customer: 'Omar Griffith',
		image: '/assets/admin/dashboard/user5.png',
		color: '#4F80E1',
	},
	{
		id: 12805,
		product: 'iBox iPhone 14Pro...',
		order: '20/03/2023,01:10',
		status: 'Cancel',
		Qty: 'x3',
		price: '1.458',
		customer: 'Omar Griffith',
		image: '/assets/admin/dashboard/user6.png',
		color: '#FB4949',
	},
];

export const addOrderData = {
	id: 12809,
	image: '/assets/admin/dashboard/user2.png',
	customer: 'Omar Griffith',
	product: 'Apple Macbook Pro lorem20 dk...',
	order: '20/03/2023,01:10',
	status: 'Waiting Payment',
	total: '400,000,012',
	credit: '400,0,012',
	debit: '400,000,012',
	balance: '400,000,012',
	materials: [
		{
			id: 12808,
			product: 'iBox iPhone 14Pro...',
			description: 'iBox iPhone 14Pro...',
			Qty: '5',
			price: '2',
			amount: '10',
		},
		{
			id: 12808,
			product: 'iBox i',
			description: 'iBox iPhone 14Pro...',
			Qty: '5',
			price: '2',
			amount: '10',
		},
		{
			id: 12808,
			product: 'iBox 14Pro...',
			description: 'iBox iPhone 14Pro...',
			Qty: '5',
			price: '2',
			amount: '10',
		},
	],
};

export const months = [
	{ value: '', label: 'All Months' },
	{ value: 1, label: 'January' },
	{ value: 2, label: 'February' },
	{ value: 3, label: 'March' },
	{ value: 4, label: 'April' },
	{ value: 5, label: 'May' },
	{ value: 6, label: 'June' },
	{ value: 7, label: 'July' },
	{ value: 8, label: 'August' },
	{ value: 9, label: 'September' },
	{ value: 10, label: 'October' },
	{ value: 11, label: 'November' },
	{ value: 12, label: 'December' },
];
