name: Deploy Node Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"


jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Deploy Backend FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        port: ${{ secrets.FTP_PORT }}
        local-dir: backend/
        server-dir: ${{ secrets.BACKEND_PATH }}
        exclude: |
          **/.env
          **/node_modules/**
          **/.git/**