name: Deploy React Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22


    - name: Install packages
      run: npm ci


    - name: Create env
      run: |
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env


    - name: Build React
      run: npm run build


    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        port: ${{ secrets.FTP_PORT }}
        local-dir: frontend/dist/
        server-dir: ${{ secrets.FRONTEND_PATH }}